theme: jekyll-theme-minimal
title:  Yanzhao Xie

description: >
  <img src="me.png"  alt="photo" height="230" align="center"/>
  <center>Lecturer,</center> 
  <center>School of Computer Science and Cyber Engineering, Guangzhou University,</center>
show_downloads: false
# logo: ./me.png
